ingress:
  hosts:
    
      paths: 
        - path: /api/
          backend:
            serviceName: backend
            servicePort: 8080
        - path: /
          backend:
            serviceName: frontend
            servicePort: 80