apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: microservice-task_backend
        name: backend
        ports:
          - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args:
          - python manage.py migrate;
            gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application
      
