services:
  backend:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    #command: python manage.py runserver 0.0.0.0:8000

  web:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    #command: npm start
    depends_on: 
    - backend
