services:
  backend:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 127.0.0.1:8000

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: npm serve build
    depends_on: 
    - backend
