ingress:
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 3000
      
      - path: /todolist
        backend:
          serviceName: backend-service
          servicePort: 8000