apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: microservice-task-ingress
spec:
  rules:
    - host: ec2-44-204-182-166.compute-1.amazonaws.com
    - http:  
        paths: 
        - path: /
          backend:
            service: 
              name: frontend-service
              port: 
                number: 3000
        - path: /
          backend:
            service:
              name: backend-service
              port:
                number: 8000
  