apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: microservice-task-ingress
spec:
  rules:
    - host: ec2-44-204-182-166.compute-1.amazonaws.com
      paths: 
        - path: /
          backend:
            serviceName: frontend
            servicePort: 3000
        - path: /api
          backend:
            serviceName: frontend
            servicePort: 8000
  