apiVersion: networking.k8s.io/v1beta1

kind: Ingress

metadata:
  name: microservice-task
spec:
  rules:
    - host: http://ec2-44-204-182-166.compute-1.amazonaws.com/
      http:
       paths:
        - path: /
          backend:
            serviceName: frontend-service
            servicePort: 3000
        
        - path: /
          backend:
            serviceName: backend-service
            servicePort: 8000
  