apiVersion: apps/v2
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: microservice-task_web
        name: frontend
        ports:
          - containerPort: 3000
        command: ["npm", "start"]
        
