ingress:
    - host: ec2-44-204-182-166.compute-1.amazonaws.com
      paths: 
        - path: /
          backend:
            serviceName: frontend
            servicePort: 3000
        - path: /api
          backend:
            serviceName: frontend
            servicePort: 8000